# Generated by Django 4.0.4 on 2022-06-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sateesh', '0004_alter_employee_emp_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.BigIntegerField()),
                ('Book_name', models.CharField(max_length=50)),
            ],
        ),
    ]
