# Generated by Django 4.0.4 on 2022-06-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sateesh', '0005_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_name',
            field=models.FilePathField(),
        ),
    ]
