# Generated by Django 4.0.4 on 2022-06-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sateesh', '0006_alter_books_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='num',
        ),
    ]
