# Generated by Django 4.0.4 on 2022-06-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sateesh', '0007_remove_books_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_name',
            field=models.FileField(upload_to=''),
        ),
    ]
