# Generated by Django 4.0.4 on 2022-06-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sateesh', '0008_alter_books_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_name',
            field=models.CharField(max_length=100),
        ),
    ]
